#!/bin/bash
set -e

# Paths
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CLIENT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
INSTALL_DIR="$CLIENT_ROOT/install"

# Configurations
TEMPLATE_FILE="$CLIENT_ROOT/../config/config_template.json"
CONFIG_FILE="$CLIENT_ROOT/../config/config.json"

echo "========================================="
echo "   LORTNOC CLIENT INSTALLATION"
echo "========================================="
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"


# --- Environment Setup -------------------------------------------------------
# Check Python
if ! command -v python3 &> /dev/null; then
  echo "Error: python3 is not installed."
  exit 1
fi
echo "[+] Python3 found."

# Setup Virtual Environment
VENV_DIR=".venv"
if [ ! -d "$VENV_DIR" ]; then
  echo "[*] Creating virtual environment..."
  python3 -m venv $VENV_DIR
fi
echo "[+] Virtual environment ready."

# Install Dependencies
echo "[*] Installing dependencies..."
./$VENV_DIR/bin/pip install -r $CLIENT_ROOT/tools/scripts/requirements.txt
echo "[+] Dependencies installed."


# --- Configuration -----------------------------------------------------------
if [ ! -f "$CONFIG_FILE" ]; then
  # Check if template exists
  if [ ! -f "$TEMPLATE_FILE" ]; then
    echo "Error: Template file $TEMPLATE_FILE not found."
    exit 1
  fi

  read -p "Enter Client Name          : " CLIENT_NAME
  read -p "Enter Discord Bot Token    : " TOKEN
  read -p "Enter Heartbeat Channel ID : " CHANNEL_ID

  python3 -c "
import json
with open('$TEMPLATE_FILE', 'r') as f:
  config = json.load(f)

config['client_name'] = '$CLIENT_NAME'
config['discord']['token'] = '$TOKEN'
config['discord']['heartbeat_channel_id'] = '$CHANNEL_ID'

with open('$CONFIG_FILE', 'w') as f:
  json.dump(config, f, indent=2)
"
  echo "[+] Configuration saved to $CONFIG_FILE."
else
  echo "[+] Configuration file exists at $CONFIG_FILE."
fi


# --- Run Script Generation ---------------------------------------------------
RUN_SCRIPT="run.sh"

# Create Run Script
cat > $RUN_SCRIPT <<EOF
#!/bin/bash
# Lortnoc Client Launcher
# Generated by install.sh

# Move to installation directory
cd "$INSTALL_DIR"

# Execute using virtual environment python
export PYTHONPATH="\$PYTHONPATH:$(dirname "$(dirname "$INSTALL_DIR")")"
"$INSTALL_DIR/$VENV_DIR/bin/python" ../sources/main.py
EOF
chmod +x $RUN_SCRIPT


# --- Systemd Service Generation ------------------------------------------------
SERVICE_NAME="lortnoc-client.service"
SYSTEMD_INSTRUCTIONS=""

read -p "Do you want to generate a Systemd service file? (y/N): " GEN_SYSTEMD
if [[ "$GEN_SYSTEMD" =~ ^[Yy]$ ]]; then
  CURRENT_USER=$(whoami)
  cat > $SERVICE_NAME <<EOF
[Unit]
Description=Lortnoc Client
After=network.target

[Service]
Type=simple
User=$CURRENT_USER
WorkingDirectory=$INSTALL_DIR
ExecStart=$INSTALL_DIR/$RUN_SCRIPT
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

  sudo mv $SERVICE_NAME /etc/systemd/system/
  sudo systemctl daemon-reload
  echo "[+] Service file installed : $SERVICE_NAME"

  SYSTEMD_INSTRUCTIONS="
To install and enable the systemd service:
  sudo systemctl enable lortnoc-client
  sudo systemctl start lortnoc-client
"
fi


# --- Completion Message ------------------------------------------------------
echo ""
echo "========================================="
echo "   INSTALLATION COMPLETE"
echo "========================================="
if [ ! -z "$SYSTEMD_INSTRUCTIONS" ]; then
  echo "$SYSTEMD_INSTRUCTIONS"
else
  echo "You can now start the client with:"
  echo "  ./$RUN_SCRIPT"
  echo ""
  echo "To run in background:"
  echo "  nohup ./$RUN_SCRIPT > client.log 2>&1 &"
fi
echo "========================================="
